### PR TITLE
Added standard Scrutinizer config

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed you had some non-standard Scrutinizer config. I think this is an improvement.

Have a nice day! [beep boop]

### CODE REVIEW

**Comment by dhensby** [comment]
Not sure how this is failing @helpfulrobot can you rebase, please?

**Comment by dhensby** [comment]
Rebase

**Comment by tractorcow** [comment]
@assertchris can you fix your robot please?

**Comment by assertchris** [comment]
I gave it a few kicks. I'd hate to be around when it works out how to operate on batteries...

**Comment by tractorcow** [comment]
Ta

**Pull request merged**
