### PR TITLE
 ENHANCEMENT: Increase test coverage from 54% to 92%

### PR DESCRIPTION
**Pull request by gordonbanderson**
1) Add test coverage using codecov.io
2) Improve test coverage from 54 to 92%
3) Two fixes, as separate commits, for tests that failed.
4) Added more badges on README.md page.

### CODE REVIEW

**Comment by gordonbanderson** [comment]
Test coverage report can be found here https://codecov.io/github/gordonbanderson/silverstripe-comments?branch=improvecoverage

**Comment by tractorcow** [comment]
Wow, good job @gordonbanderson !

**Comment by gordonbanderson** [comment]
Cheers @tractorcow :)   Note that you will need to log in to Scrutinizer with the SilverStripe account and enable this repository though - the Scrutinizer badges are not showing on https://github.com/silverstripe/silverstripe-comments

**Comment by tractorcow** [comment]
I've setup https://scrutinizer-ci.com/g/silverstripe/silverstripe-comments/

**Comment by gordonbanderson** [comment]
Looks like it was set up 2 years ago but have never been run (at least no public evidence available)

**Comment by tractorcow** [comment]
Oops, the badges are pointing at your fork, mate. :dancer: 

Can you please fix those?

image

**Comment by gordonbanderson** [comment]
Aaaargh, though I had.  OK

**Comment by gordonbanderson** [comment]
Fix on https://github.com/silverstripe/silverstripe-comments/pull/155

BTW the tool I am using to create these, as it's frustrating and time consuming to do manually is here https://github.com/gordonbanderson/Badger

**Comment by gordonbanderson** [comment]
The Travis build also failed as my multiple --require flags option was merged into the main SilverStripe repo.  I'd deleted the temporary branch after the merge.  Fixed and pushed on same branch, Travis is passing.

**Comment by tractorcow** [comment]
Do we still need to fix https://github.com/silverstripe/silverstripe-comments/blob/master/.travis.yml#L45?

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-comments/commit/1d63b8d3234d80060b96c7838bacd0d64f44ced6, thanks @dhensby

**Pull request merged**
