### PR TITLE
Fix potential ambiguous column issue.

### PR DESCRIPTION
**Pull request by janneklouman**
Solves #202

### CODE REVIEW

**Comment by janneklouman** [comment]
Where does the `DataObject".` prepend to the `AND` conditions come from?

See for example [line 301 here](https://travis-ci.org/silverstripe/silverstripe-comments/jobs/254129657#L301)

`[...] AND ("DataObject"."Comment"."ParentID" = ?)`

Something to do with the test environment? What am I missing here?

**Comment by robbieaverill** [comment]
Possibly [here](https://github.com/silverstripe/silverstripe-comments/pull/213/files#diff-ce6dcc4c0bbb3959ffa6d945016e0e27R28)?

**Comment by dhensby** [comment]
I've noticed that you've created this pull request from one of the "core branches" rather than a branch specifically intended for this pull request. This can cause problems if we ask you to target this PR at a different branch.

In the future please create a new branch for each individual pull request. See our [guide about contributing PRs](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request)

**Comment by robbieaverill** [comment]
I don't think this approach will work, since the CommentList uses the foreign key (in field name form) to add and remove relationships. Perhaps we can find a more specific place where this field is being used in the filter and make it more explicit at that point?

**Comment by janneklouman** [comment]
OK, that sounds good. I'm not too fond of this work-around. I'll close this pull request, but leave the issue open and we can take it from there.

**Pull request closed without merging**
