### PR TITLE
FIX: Redirect moderation to #moderation instead of #PostCommentForm_error

### PR DESCRIPTION
**Pull request by gordonbanderson**
Fix for #168

### CODE REVIEW

**Comment by dhensby** [comment]
@gordonbanderson thanks for this @silverstripe/core-team is there anyone that can verify this?

**Comment by dhensby** [comment]
needs rebasing

**Comment by tractorcow** [comment]
I would make a separate PR if you want to fix so many whitespace changes. The actual changes to code here is small by comparison...

**Comment by gordonbanderson** [comment]
This module does need a PSR-2 sweep, .editorconfig is picking up and fixing the errors.

**Comment by tractorcow** [comment]
I did that at https://github.com/silverstripe/silverstripe-comments/pull/180; @dhensby can you merge it?

**Comment by dhensby** [comment]
Merged, rebase please

**Comment by gordonbanderson** [comment]
Rebase done, there are still a few whitespace changes in the template files though.

Guess I will need to rebase other un-merged pull requests also.

I'm intending to have a look at this module at the weekend as I have a client who wishes hierarchical comments.

**Comment by tractorcow** [comment]
There's a missing and necessary PHP change for this pull request to work.

https://github.com/silverstripe/silverstripe-comments/pull/173/files#r57635758

**Comment by tractorcow** [comment]
@gordonbanderson please PR just that change and confirm that it works.

**Comment by dhensby** [comment]
bump @gordonbanderson

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-comments/pull/183

**Pull request merged**
