### PR TITLE
API Move configuration of comments to the config API and enable per-instance configuration

### PR DESCRIPTION
**Pull request by tractorcow**
If this is merged it'd probably be a good idea to branch the current master into 1.2 first.

Rather than using static properties in the `Commenting` class we just use the config API and assume that any class with the `CommentsExtension` has commenting configured.

* Commenting is no longer enabled for SiteTree automatically by default.
* Update use of config within the module to get the config either from the specific object being commented on, or using the default config from the extension itself.
* Lots of code cleanup, phpdoc, indentation
* A new `enabled` option has been specified in case any class with the extension needs to have the functionality disabled.
* Also included is a new `CommentList` relation list to wrap a comment list bound to a specific parent.
* `EscapedComment` has been configured to work more nicely with the casting mechanism.
* Deprecation has been updated to 2.0 and some methods updated with this notice. `Commenting` class has been completely deprecated.
* Spam comments are now no longer displayed at all in the frontend; It's necessary for admin users to manage these via the modeladmin. This is because sifting through non-spam comments on the frontend of a site with heavy spam volume is near impossible. Users can still customise this list for display via the `updateComments` extension point on the parent object.
* Comments list has been broken into `Comments` and `PagedComments` methods, so frontend developers can customise how paging is done. `AllComments` can also be called to retrieve spam / unmoderated comments for internal use.
* Instead of displaying all spam comments on the frontend, a new per-page comment moderation system is available, so that users, admins, or editors with limited CMS permissons are still able to edit a specific page and manage comments just for that page.

This work is the groundwork for the following features yet to come:

* Improved comment moderation system (UX review implementation)
* Nested comments
* Ability to control comment options per-page via CMS settings

### CODE REVIEW

**Comment by sminnee** [comment]
I've had a look at the CommentList implementation and usage; it looks good to me—nice use of a custom DataList subclass! :-)

It did expose some issues to do with the underlying API (the fact that you couldn't use `filter()` to adjust the query was frustrating) but this can be picked up as a low-priority SilverStripe 4.0 change if we want.

**Comment by tractorcow** [comment]
In 3.2 we won't even need this class; The polymorphic relation will work out of the box. :)

**Comment by tractorcow** [comment]
This has been updated. I've renamed the config to `CommentsGridFieldConfig`

**Comment by sminnee** [comment]
Hey @wilr Damian has refactored commenting config to use the SilverStripe config system, which means that the configuration can go into YML. Make sense to you for a 2.0 comment module release?

**Comment by sminnee** [comment]
Ok - I'm gonna assume @wilr is all good with this and merge... :-)

**Comment by tractorcow** [comment]
yay so much

**Comment by tractorcow** [comment]
Thanks @sminnee  :D

**Comment by tractorcow** [comment]
I've created a 1.2 branch to maintain the API for the commit prior to this.

see https://github.com/silverstripe/silverstripe-comments/tree/1.2

**Comment by wilr** [comment]
Sorry team, was in a cave. Nice work. Statics were pre config API so all good. Good work on the mods. Glad to see comments getting love.

**Comment by tractorcow** [comment]
cave

**Pull request merged**
