### PR TITLE
FIX: Layout with Gravatar fixed

### PR DESCRIPTION
**Pull request by gordonbanderson**

### CODE REVIEW

**Comment by gordonbanderson** [comment]
Fix for #158

**Comment by gordonbanderson** [comment]
After fix looks like this
gravatarfix

**Comment by tractorcow** [comment]
@scott1702 / @flashbackzoo please approve of this change.

**Comment by dhensby** [comment]
@scott1702 @flashbackzoo

**Comment by scott1702** [comment]
Just tested it out and its all good, sorry for the wait @gordonbanderson.

**Pull request merged**
