### PR TITLE
FIX: Badges now pointing at SilverStripe master

### PR DESCRIPTION
**Pull request by gordonbanderson**
Fix for incorrect badges that slipped through my checks

### CODE REVIEW

**Comment by dhensby** [comment]
In this instance you'd want to rebase against the upstream master branch

closed with 43a2414

**Comment by tractorcow** [comment]
@dhensby you need to include the .travis.yml fix as well I think.

**Comment by dhensby** [comment]
derp

**Comment by gordonbanderson** [comment]
"@dhensby In this instance you'd want to rebase against the upstream master branch" < can you just briefly explain the correct procedure here.  I'm familiar with the rebasing part, upstream in this case is my local copy?

And note to self, having had my head in Travis for the last monght, actually wait until the Travis build has finished... (in this case it was a text change so I pushed it immediately not realising the Travis file issue)

**Comment by dhensby** [comment]
@gordonbanderson sorry, I think I got the wrong end of the stick with this.

What you probably wanted to do was create a new branch from master and cherry-pick your commits - rather than merge your own changes

**Pull request closed without merging**
