### PR TITLE
Minor: Turn off line numbers for generated CSS

### PR DESCRIPTION
**Pull request by gordonbanderson**
Some of the other issues I've raised, and fixed, require CSS changes, and without the line numbers existing merging is easier.  I will post the other pull requests that alter CSS on the assumption this one is merged first.

### CODE REVIEW

**Comment by gordonbanderson** [comment]
Mmmm, this might easier as one pull request to fix several issues

**Comment by tractorcow** [comment]
If we are removing line numbers, can we please enable sourcemaps? `sourcemap = true`

**Comment by gordonbanderson** [comment]
I wasn't aware the sourcemap option existed.  Does this look correct https://github.com/gordonbanderson/silverstripe-comments/commit/298f0698a1cd2e250c87431ec94856a430ab75d4?  if so I will rebase back onto the original pull request branch.

**Comment by tractorcow** [comment]
Yep thats good. :D

**Pull request merged**
