### PR TITLE
FIX: Include CMS in suggested packages

### PR DESCRIPTION
**Pull request by gordonbanderson**
Fix for #151

### CODE REVIEW

**Comment by tractorcow** [comment]
That old `suggest` flag is not implemented properly: The value part should be the description, not the version constraint. :) Want to fix this?

**Comment by gordonbanderson** [comment]
Aaaaaaaaargh, so it is https://getcomposer.org/doc/04-schema.md#suggest - which totally invalidates https://github.com/silverstripe-labs/silverstripe-travis-support/pull/23 :(

**Comment by tractorcow** [comment]
Oh, right... exactly. :)

**Comment by gordonbanderson** [comment]
New pull request submitted https://github.com/silverstripe/silverstripe-comments/pull/153

**Pull request closed without merging**
